### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by neuromancer** [Raptor007/RaptorEngine#1]
Hi,

I wonder if it will be possible to have a Linux version of the raptor engine. Is there any plan for it?

**Comment by Raptor007** [comment]
Hello!  RaptorEngine should work on Linux.  I use it on Slackware Linux myself, as well as Windows and Mac OS X.  Are you having specific Linux compatibility problems?

The Makefile in X-Wing Revival tries to automatically configure itself for each platform, with the default `LIBDIR=/usr/lib64` used for the Linux library path:
https://github.com/Raptor007/X-Wing-Revival/blob/master/Makefile

I'm sorry, I know that's kind of a messy Makefile right now.  On my to-do list is to create an easy sample project that you can use to get started, with a cleaned up Makefile.  :¬)

**Comment by neuromancer** [comment]
> Hello! RaptorEngine should work on Linux. I use it on Slackware Linux myself, as well as Windows and Mac OS X.

That is great news!.

> The Makefile in X-Wing Revival tries to automatically configure itself for each platform, with the default LIBDIR=/usr/lib64 used for the Linux library path:
> https://github.com/Raptor007/X-Wing-Revival/blob/master/Makefile
> I'm sorry, I know that's kind of a messy Makefile right now. On my to-do list is to create an easy sample project that you can use to get started, with a cleaned up Makefile. :¬)

I did a quick try to compile it using the Makefile, but unfortunately, I got this:

```bash
$ make
$ g++ -c  -march=native  -O3 -fomit-frame-pointer -ftree-vectorize -fno-strict-aliasing -flto -Wall -Wextra -Wno-multichar -Wno-unused-parameter   -ISources -ISources/Game -ISources/UI -I/opt/local/include -I/opt/local/include/SDL -I/usr/local/include -I/usr/include  Sources/Main.cpp -o build/arch-native/XWing/Main.o
In file included from Sources/Main.cpp:7:0:
Sources/XWingGame.h:8:30: fatal error: PlatformSpecific.h: No such file or directory
 #include "PlatformSpecific.h"
                              ^
compilation terminated.
```

Also, I think it is quite important to have a small README file clearly saying which platforms are supporeted (e.g Windows, MacOS and Linux) and how to compile it in each platform. And some screenshots too! :smile:

**Comment by Raptor007** [comment]
You're right, I really haven't documented this very well for anyone else to build.  Sorry about that!  It's on my to-do list.  :¬)

> `fatal error: PlatformSpecific.h: No such file or directory`

RaptorEngine needs to be adjacent to your project directory, such as:
~/src/X-Wing-Revival
~/src/RaptorEngine

Then `$(wildcard ../RaptorEngine/*)` in the Makefile will add the necessary include paths: https://github.com/Raptor007/X-Wing-Revival/blob/master/Makefile#L37

You'll also need to have SDL 1.2, GLEW, and OpenVR installed.  You can probably get most of these from your package manager.  OpenVR is available here:
https://github.com/ValveSoftware/openvr

(Or you can set `CFLAGS = -DNO_VR=1` and remove references to `libopenvr_api.so` from the Makefile.)

After you build the executable, you'll also need the assets from the game zip file to play it:
http://www.mediafire.com/file/o7b5164q06qjc7l/X-Wing%20Revival%200.1.6%20Alpha.zip

**Comment by neuromancer** [comment]
Great!, so the build seems to work. My recommendation is to try to detect the installation of openvr and disable it if it is not available. I will try to test X-Wing Revival in detail next week. Thanks!
